#!/bin/bash

WEBHOOK_URL="https://hooks.slack.com/services/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"

COMMIT_MSG=$(git log -1 --pretty=%B)
COMMIT_AUTHOR=$(git log -1 --pretty=%an)
COMMIT_HASH=$(git rev-parse HEAD)

payload=$(cat <<EOF
{
  "text": "📌 New Commit Pushed\nAuthor: $COMMIT_AUTHOR\nMessage: $COMMIT_MSG\nCommit: $COMMIT_HASH"
}
EOF
)

curl -X POST -H 'Content-type: application/json' \
--data "$payload" \
$WEBHOOK_URL
